# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-memx-runtime"
BBFILE_PATTERN_meta-memx-runtime = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-memx-runtime = "6"

LAYERDEPENDS_meta-memx-runtime = "core"
LAYERSERIES_COMPAT_meta-memx-runtime = "mickledore styhead walnascar scarthgap"
